### PR TITLE
HoI4 further 1.5 update

### PR DESCRIPTION
**Pull request by IohannesIohannium**
-Added OCC flags from Vic2
-Added HPM jewish_cultures culture group
-Icons for culture-ideas
--Somebody to actually better draw the new ones is welcome, they currently look like '90's jpgs
-All generic cultural unions of Vic2 can now be created (Arabia, Scandinavia, UK, France, Yugoslavia, Romania, Hungary, Czechoslovakia, Russia, India, Poland-Lithuania, United Baltic Nations, Germany, Italy)
--Those tags are supposed to be ALWAYS coded. The decisions are blanked out for now.
--Country color won't change, sadly
-Missing radical and absolutist flags for union nations added
-Fixed the Ottomans<->Turkey name switching decisions
-Fixed Detroit and Buea (Cameroon) giving weird mappings, and Agades (Niger) giving split states
-Fixed Macedonian, Kosovar, and Montenegrin borders
-Fixed Slavgorod-in-Kokshetau enclave, fixed Peremyshl-missing-province (HoI3236)
-Fixed Uruguayan border
-Fixed locations of some cities (may cause enclaves, didn't see if)
-Added Barbarian and new flags from Vic2
-Added icons for cultural ideas
-Added new cultures (Gypsy, Brithenig, Gaul, Läßin)
-Removed some "generics" portraits
--The zz_ file contains the one that doesn't use historical figures
-Added missing absolutist and radical portraits in case of in-game random leader generation
-Fixed the "release button" going canine
-Added some names
-Added OP modifiers to the easter egg cultures (Cats, Horses, Bears, Undead, and Aliens)
-Added female surnames for ethnicities that would need them
-Added descriptions to the cultural ideas (better revision for translation would be welcome)
-Added HFM cultures

### CODE REVIEW

**Comment by Idhrendur** [comment]
An all-inclusive pull request is too much to review. I need this to be split into smaller, more focused ones, such as one for flags, one fixing the graphics issue, one for the cultures, etc.

Also, you totally stomped on the updated spanish localisations we were given. You need to make sure to pull the latest from the main repository before doing your work in your repository.

**Comment by IohannesIohannium** [comment]
Ah, sorry, I'll do fix this tomorrow. Also, I pulled it from the latest I could find.

**Comment by Idhrendur** [comment]
Thanks!

**Comment by IohannesIohannium** [comment]
For the other remaining parts, I could not manage to get a pull request somehow. Here I leave them as .zips:

## GFX and name conversion update
(to put directly into /Data_Files)
[Vic2HoI41.5D.zip](https://github.com/Idhrendur/paradoxGameConverters/files/1984322/Vic2HoI41.5D.zip)

Added HPM culture groups and a historical figures' based conversion. Also added female surnames.
## MAP conversion
(again, to put directly into /Data_Files)
[Vic2HoI41.5E.zip](https://github.com/Idhrendur/paradoxGameConverters/files/1984336/Vic2HoI41.5E.zip)
Fixed some minor border tweaks, notably:
-Cameroonian-Nigerian border
-Split Agades (Niger) state
-Serbian Southern borders
-Uruguayan border with Brazil
-Some cities' locations
## Generic portraits fix
(to put into /Data_Files/blankMod/output)
[Vic2HoI41.5F.zip](https://github.com/Idhrendur/paradoxGameConverters/files/1984339/Vic2HoI41.5F.zip)
A little edit that gives continental default "Absolutist" and "Radical" portraits. This is to ensure that, in case of an ideological change, there won't just be a grey suit.

Here I ended splitting the 1.5 further update, with these above and the pulls #536, #537, #538, and #539.

**Comment by IohannesIohannium** [comment]
Update has been split finally into #536, #537, #538, #539, #558, #559, and #560.

**Comment by Idhrendur** [comment]
Thanks!

**Pull request closed without merging**
