### PR TITLE
Factory cleanup

### PR DESCRIPTION
**Pull request by woggy**
No factories absolutely require local RGO inputs. Remove code for dealing with this case, since it was never being run anyway.

(Sorry for the mess with commits. Someday I'll remember what I'm doing with git.)

### CODE REVIEW

**Comment by kratostatic** [comment]
Just to check, it looks like you've reverted the Vic2 adjacencies commit here which I thought was the problem with the factories not being converted properly.  Otherwise this has all the same commits as pull request #333 so I'm inclined to just merge this one and un-revert that commit.

**Comment by woggy** [comment]
Oh, sure, if you can get both feature commits from one branch I'm all for that. Was trying to keep things reasonably separate in the pull requests but may have done more harm than good.

**Comment by kratostatic** [comment]
Yeah if I merge this one then I get everything in 7 commits.  If I merge both it'll be at least 11 and I'll probably have to fix some file conflicts.  Plus your commits are sufficiently clear I know what's you've done in each.

**Comment by woggy** [comment]
Just noting that the adjacencies commit still needs un-reverting.

**Comment by kratostatic** [comment]
Yeah I know, I'll be sorting that out later on.

**Comment by woggy** [comment]
Okay! Didn't mean to be pushy, just wanted to make sure we were all on the same page. :)

**Pull request merged**
