### PR TITLE
Vic2 to hoi4 - Small changes & additions

### PR DESCRIPTION
**Pull request by Johuotar**
Hi I started to think that these small changes I made could be beneficial to be added to the converter project. Stuff included:

1. Fix to Absolutism focus: add_ideas = absolutism"; instead of add_ideas = absolutist";

2. Nerf to monarchy ideas and great power ideas. Major countries democracy tree no longer gives militarism idea and send volunteers rule is there only once instead of twice. National unity gains nerfed.

3. Added icons to some monarchy ideas & removed research speed bonus from GP idea.

### CODE REVIEW

**Comment by Hamiller78** [comment]
Hi! I was asked to do a little review since I did a lot of the focus tree stuff.
First of all thanks for contributing. Of course balancing improvements are a tricky topic. So let me first translate what the changes mean:
1. This fix is already in the current development branch. Somebody was faster. ;-)
2. The first two are boni from the absolutist focus tree. I must admit I haven't touched this since I took over from Thatsgerman and never looked at the numbers. The local_resources_factor improves the excavation of resources. Tech in the base game improves in 10% steps, Yugoslavia has an idea for 10% (and they have to catch up with Great Powers). So I would agree that 15% is too high.
Second one is a bonus to research time: Reducing from 10% to 3%. This bonus exists in the base game for some countries and is typically 5%. So yes, the proposed 3% is closer to the base game.
The proposed change in ideas/powers.txt is scrapping most of the Great Power boni. @Idhrendur: That's a general decision. How valuable should it be to end up in Victoria 2 as a Great Power?
The next proposed change is changing Military Focus for democracies to 2% to national unity. I actually played with the first one and have to agree that it's ridiculously strong. You get a big chunk of manpower with one just one focus while fascist states have to spend a lot of political power to switch recruitment laws. 2% national unity seems weak though. A typical value in the base game is 5%.
Next one is the double allow volunteers. Yeah, we just need a good replacement. 120 political power as a replacement isn't to interesting either. I might just shorten the branch (we currently have two War Propagandas).
Next one is nerfing national unity gain in the Absolutist branch from 10% to 2%. I find 2% too low. As said above, in the base game it's typically 5%.
3. Proposal for pictures for some ideas which currently have none. I didn't notice, perhaps that's why I get advisor names for some ideas...
And here he reduced the Great Power bonus is reduced a bit more so that they only get a fight bonus on their core territory.

Summary: Most proposals are reasonable, I just find the national unity gains of 2% too small. And we have to make a general decision whether Great Powers should get big advantages or not. I think some boni are okay to replicate the Great Power status from Victoria 2, but in most fields they should already be superior due to the bigger industry and military without widening the gap to secondary powers even further.

**Comment by Idhrendur** [comment]
@Hamiller78 I was never the biggest fan of the GP idea in the first place. To my mind, the effort of becoming a GP creates it's own rewards in military and industry. But it's been a useful stop-gap while other systems were implemented in the converter. So I have no problem with it being significantly weakened.

I'll leave it to you to merge the pull request whenever you think it's good enough to go.

**Comment by Johuotar** [comment]
I do like there being a GP idea just so I can check which countries were GP in Vic2 since they have more interesting focus trees.

I've been thinking about the question of balancing manpower conversion & focuses. In vanilla majors don't really get any focuses that give manpower since they don't need any. SU can get some manpower but most don't. The converter gives the 7% bonus of generic nations to every countrys focus tree, which can result in absurd amounts of free manpower in fascists majors. I've been thinking if the generic manpower boosts should be nerfed a bit or if majors will eventually have some other focuses instead of those generic political focuses then it could help balance manpower values.

I do agree that 2% unity is too low for a focus. 5 would be fair. The next patch will change everything though, since then every country works the same (with some exceptions like France).

> Q: So how do you capitulate an enemy country now?
> Archangel85: 80% of VPs occupied, but we are experimenting with low stability/literally being France lowering that threshold 

Hey I can see if I have time to change the unity boost to 5 and mayby create new purpose for the second war propaganda focus and better reward for the other volunteer focus than pp.

**Comment by Johuotar** [comment]
I changed limited intervention to give this bonus instead of pp: 
tensionlimit

Should help democratic countries do something, the tension limits can be a bit high in converted games.

The second war propaganda focus is now called prepare intervention and war propaganda and the monarchy equivalent focus give 5% unity.

**Comment by Hamiller78** [comment]
Thanks for the improvements! I will merge them now.

**Pull request merged**
