### PR TITLE
CK2Plus compatibility (proposal)

### PR DESCRIPTION
**Pull request by IhateTrains**
Some CK2+ mod cultures and religions are not mapped. After I added them, the converter worked fine. Unfortunately, not every religion has its equivalent in Vicky 2, so I attached them to the closest possible ones.

### CODE REVIEW

**Comment by kratostatic** [comment]
I'll have a proper check of this tomorrow at some point - it's too late to be messing about with merge conflicts.

**Comment by kratostatic** [comment]
Culture stuff looks good, I can sort out the conflict.  Long term it might be worth adding a couple of these cultures to the Vicky 2 mod.

Any particular reason you've decided I don't program?

**Comment by IhateTrains** [comment]
I copied the ReadMe file from Ihrendur's fork, isn't it up-to-date?

**Comment by kratostatic** [comment]
Yes it is, albeit I hadn't realised I'd only changed it on my fork.  My actual "job" on the converter is programming - although I do the odd bit of data file fixing that credit comes from a bunch of culture fixes I did about 18 months ago.

**Comment by IhateTrains** [comment]
Should I fork Ihrendur's fork instead of your one?

**Comment by kratostatic** [comment]
Yeah, I've got full access to his fork now.  I'll probably save my fork for anything experimental.

**Pull request merged**
