### PR TITLE
Windows support for portable parser (proposal)

### PR DESCRIPTION
**Pull request by hansvanmoer**
This is a proposal to include a Windows version of the codecvt facet implementation using From/ToMultiByte from the WIN32 API. It took me some time to get this to work on all versions of Windows (tested on XP, Vista and 10).

The effect of this (when I finish editing the build file) will be that the generic parser (parser_generic::parse*) can be used on both Windows and Linux for all encodings (UTF-8, Latin-15, UTF-16 LE) without the need to support a separate versions for each OS. The only OS specific code needed is located in ConversionFacetUtils.h, which defines the char <-> wchar_t conversions needed by codecvt for ifstream and ofstream. Because I've not yet tested the parser on non Vic2 files the generic parser is only set as the default one on Linux so as not to inconvenience others (I don't want to be crucified if it breaks other people's builds :) ). It can be used in Windows builds by calling it directly or setting the preprocessor define.

Changes:

- Added Windows version of Conversion type that encapsulates the encoding/deconding strategy
- Implemented lookahead functions to check UTF-8 octet strings before passing them on to the Windows API since incomplete input string error handling is inconsistent between versions (missing trailing octets result in the whole string not being translated in XP).

Notes:
- wchar_t -> UTF-8 conversion can probably be optimized. I've not yet found a suitable Windows API function to replace ToMultiByte so I've implemented a solution that will be somewhat sub-optimal for small files but still reasonably fast for large buffers. It isn't noticeably slow in any case.

One question (probably a stupid one, but I'm not very familiar with Visual Studio): Visual studio complains that I should build the source against Windows XP. Does this mean that Windows XP is the target platform for the Vic2HoI4Converter and that I should use Visual Studio 2015 to compile and test the code ? Retargeting the code to Windows10/VS2017 works but will probably result in many changes in the project files.

As I'm not sure about this, I've not yet added the modified Visual Studio project files: the pull request is not yet complete. Please respond on this thread to communicate if you agree with the proposed additions. If so, I'll commit the modified build files as well and complete the merge request.

### CODE REVIEW

**Comment by Idhrendur** [comment]
That all sounds good to me. I'm not entirely familiar with the warning VS is giving you, but I have kept the target build against XP. That may be less necessary these days, but I suspect we'll find a number of people unable to use the converter if we change that. You can always just add the build files and I'll take a look and try to fix it up as needed.

How well is this working on Linux currently? Ar ewe ready for a Linux release? Because we're just about ready for a HoI4 1.4 compatibility release.

**Comment by hansvanmoer** [comment]
I'll download VS 15 then, to make sure it doesn't mangle the build files and test it with that. As far as I can see Linux conversion works fine. I'll retest the conversion for every save game in the Vic2Save folder to check if it works and let you know the results. I assume I should test against HOI4 1.4 ?

**Comment by Idhrendur** [comment]
Yep! There are a couple of errors still if you load up in HoI4, but the latest changes should work for most of the saves.

**Comment by hansvanmoer** [comment]
OK, I'll try to retest all supplied save files in Linux first. When is the release scheduled ?

**Comment by Idhrendur** [comment]
Whenever all three threads of development are in a good enough state:

- Your work
- My tracking down of load errors in HoI4 (and testing the existing saves for such things)
- @Hamiller78's work investigating a focus tree error

There's no hard deadline, though.

**Comment by hansvanmoer** [comment]
I retested most of the saves that came with the project and playtested the resulting mods for a few months. Everything seems to be working OK. I couldn't test the HPM ones because I don't have that installed currently (will do that tomorrow).

I also merged the upstream and had to change two things to get it to compile with GCC on Linux:

HOI4Version supplies an overloaded operator<= and operator>> with a non-const reference parameter, which GCC doesn't like so I had to change it to a const reference. I also had to declare the operator>> in the header to get rid of a linker error.

**Comment by Idhrendur** [comment]
I forgot to follow up with this. Was there anything else you needed to test or add, or is it ready to merge?

**Pull request merged**
