### PR TITLE
Strengthen great powers

### PR DESCRIPTION
**Pull request by wzh190015**
great powers will get 4 reseach slots and a national sprit.

### CODE REVIEW

**Comment by wzh190015** [comment]
Many characters cannot be included in Visual Studio chinese version's charset GB2312. So I have to replace all the '?'s with octal digit. The convert will not find path if any Chinese characters is included in the path.

**Comment by Idhrendur** [comment]
Oooh, you're perfect for trying to finally get a solution to the non-ASCII character issue (though I'm not sure just how GB2312 will interact with everything). I'm told that internally, Windows uses UCS-2/UTF-16 strings for paths. If you hard code paths that contain those paths in the correct format, does Windows find them? And if so, does their UTF-8 expression get properly converted to the UTF-16 form? And if that is somehow true, does the UTF-8 form get properly read from the configuration file? And assuming all that has worked and not needed fixing, does the Frontend properly save things in the config file? Does it get the paths correctly when using the browse button?

Sorry to ask you do such an extensive investigation, but I literally cannot do this investigation on my computer, as English-only Windows works differently with all of this.

**Comment by Idhrendur** [comment]
Also, you should edit readme.txt in data_files and add yourself to the credits.

**Comment by wzh190015** [comment]
The browse button get path correctly

and save it to the config file correctly
It is also correct in UCS-2 form

but the converter cannot find path

**Comment by Idhrendur** [comment]
Oh, curious. I had assumed that configuration.txt would be UTF-8 and not UCS2. Hmm, are you able to edit configuration.c to use the 'ASCII' parser? Can it read your configuration file? And if so, what representation are the characters internally?

Actually, could you upload that configuration.txt somewhere so I can do some tests myself this weekend? Thanks!

**Pull request merged**
