### PR TITLE
Vic2 to hoi4

### PR DESCRIPTION
**Pull request by Hamiller78**
Hi Idhrendur,

as the comment says, I worked some more on the national foci and loosened requirements (mostly distance, strength ratio to target). Now also "evil" (jingoistic democracy or non-democracy) non-Great Powers will get a simple focus for a war against a neighbor country. I pushed these little foci back to 1940, since in a test they caused a world war themselves. And that wasn't my intention.
I later want to give them different activation dates depending on the relations of the attacker to the target.

Radical governments were missing their own war tree altogether, I gave them the absolutist tree as an temporary solution. I'm not sure what an anarcho-liberal state would have looked like: Corporate run? But taht sounds more like SciFi than mid of 20th century. Still I could imagine them securing resources by conquering.

The pull request still contains my merge from you, but that doesn't seem to do anything, so we should be fine.

I still have to commit the changes in the governmentMapping.txt we discussed in the forum. But now I want to go to bed. ;-)

Cheers,
  Torben

P.S.: The AI currently has a problem with building planes, expecially whena country starts with 0 planes. I think I saw something about this in one of the big modding threads. I should have taken a note where. :-(

### CODE REVIEW

**Comment by Idhrendur** [comment]
Would you do a quick clean-up pass before I merge it? Some things I noticed:
- you can just go ahead and delete the commented-out code in generateWars()
- with generateDemocracyWars() always being called, it should probably be merged into the loops in generateTotalitarianWars().
- with that done, generateTotalitarianWars() should probably be renamed generateInitialWars() or something.
- in generateAdditionalWars(), you can just delete the commented-out code.
- LeaderCountries should probably be changed from a vector to a set or a map, since it's just being used to check if it was already used or not.
- Really, putting countries into that container should be moved out into a completely separate function, but that's an existing flaw, so no need to change it now.
- in calculateEvilness(), you can just delete the commented out code
- in calculateEvilness(), GC should be renamed 'country', as it's now more general.
- in fascistWarMaker(), the commented-out distance check should just be deleted (somewhere around line 1250)

All detail-level stuff. Good thinking on the overall changes!

**Comment by Hamiller78** [comment]
Thanks for the review! Do I have a few more days more days until the next release? I did the easy clean-ups right now. But for putting generateDemocracyWars() into generateTotalitarianWars() and for the role of the LeaderCountries vector I'd like to change more thoroughly to make the code more consistent.

**Comment by Idhrendur** [comment]
I don't anticipate a release before next weekend, possibly longer than that. Getting back up to speed is taking me a while.

**Comment by Hamiller78** [comment]
Okay, I cleaned up the stuff you mentioned plus some more. There is probably more, but I think it's a nice improvement.

**Comment by Idhrendur** [comment]
Good fixes!

One more fix that I should have noticed before:
Can you merge the two loops in generateMajorWars()? Use the condition
 		if (country.second->isHuman() || country.second->isGreatPower())
Or maybe create a small function that'll say if a country is major (you can reuse it for the check in generateAdditionalWars())

**Comment by Hamiller78** [comment]
Good point. It's in now.

**Pull request merged**
