### PR TITLE
Origin/vic2 to ho i4 release 0.1

### PR DESCRIPTION
**Pull request by kingofmen**
Added support-artillery regiments if there are artillery brigades left over. Some code cleanup.

### CODE REVIEW

**Comment by Idhrendur** [comment]
I just was working on some features of my own, and noticed that the force_multiplier setting wasn't in the configuration file. Could you add it to the master copy in data_files, and also work it into the frontend's data file (Vic2toHoI4DefaultConfiguration.xml)? Thanks!

**Comment by kingofmen** [comment]
Not quite with you there; the frontend does not, so far as I can discover, have a VictoHoI4DefaultConfiguration XML file. It does have one for each of the other converters, so perhaps this is an oversight? At any rate I added the line to configuration.txt.

**Comment by Idhrendur** [comment]
Sorry, I should have been more clear. Vic2toHoI4DefaultConfiguration.xml is in Vic2ToHoI4/Data_Files/. It gets copied to the frontend's directory as part of the build process.

**Comment by kingofmen** [comment]
Oh, right. Didn't realise I hadn't gotten that change into the release branch. Worked fine on my dev branch. :)

**Pull request merged**
